"""
Macro Exporters: Standalone Python Script & AutoHotkey (.ahk)
Generates portable automation scripts with tiered feature parity.
"""

from shohoj_macro.core.events import MacroEvent, EventType
from shohoj_macro.version import __app_name__, __author__, __version__


class MacroExporter:
    """Exports macros into standalone execution formats."""

    @classmethod
    def export_to_python_script(cls, events: list[MacroEvent], filepath: str, loops: int = 1, speed: float = 1.0) -> bool:
        """
        Exports a self-contained, standalone Python script with embedded WindMouse physics.
        Requires only standard library + ctypes.
        """
        script_content = f'''# Generated by {__app_name__} v{__version__}
# Developed by {__author__}
# Standalone execution script (No GUI required)

import time
import math
import random
import ctypes
from ctypes import wintypes

# Enable 1ms Windows timer
winmm = ctypes.WinDLL("winmm.dll")
winmm.timeBeginPeriod(1)

user32 = ctypes.WinDLL("user32")

INPUT_MOUSE = 0
INPUT_KEYBOARD = 1
MOUSEEVENTF_MOVE = 0x0001
MOUSEEVENTF_LEFTDOWN = 0x0002
MOUSEEVENTF_LEFTUP = 0x0004
MOUSEEVENTF_RIGHTDOWN = 0x0008
MOUSEEVENTF_RIGHTUP = 0x0010
MOUSEEVENTF_WHEEL = 0x0800
MOUSEEVENTF_ABSOLUTE = 0x8000
KEYEVENTF_KEYUP = 0x0002
KEYEVENTF_UNICODE = 0x0004

class MOUSEINPUT(ctypes.Structure):
    _fields_ = [("dx", wintypes.LONG), ("dy", wintypes.LONG), ("mouseData", wintypes.DWORD),
                ("dwFlags", wintypes.DWORD), ("time", wintypes.DWORD), ("dwExtraInfo", ctypes.c_ulonglong)]

class KEYBDINPUT(ctypes.Structure):
    _fields_ = [("wVk", wintypes.WORD), ("wScan", wintypes.WORD), ("dwFlags", wintypes.DWORD),
                ("time", wintypes.DWORD), ("dwExtraInfo", ctypes.c_ulonglong)]

class _INPUT_UNION(ctypes.Union):
    _fields_ = [("mi", MOUSEINPUT), ("ki", KEYBDINPUT)]

class INPUT(ctypes.Structure):
    _fields_ = [("type", wintypes.DWORD), ("u", _INPUT_UNION)]

def get_cursor_pos():
    pt = wintypes.POINT()
    user32.GetCursorPos(ctypes.byref(pt))
    return int(pt.x), int(pt.y)

def send_mouse_move(x, y):
    v_left = user32.GetSystemMetrics(76)
    v_top = user32.GetSystemMetrics(77)
    v_w = user32.GetSystemMetrics(78) or user32.GetSystemMetrics(0)
    v_h = user32.GetSystemMetrics(79) or user32.GetSystemMetrics(1)
    norm_x = int(((x - v_left) * 65536) / v_w)
    norm_y = int(((y - v_top) * 65536) / v_h)
    inp = INPUT(type=INPUT_MOUSE, u=_INPUT_UNION(mi=MOUSEINPUT(dx=norm_x, dy=norm_y, mouseData=0, dwFlags=MOUSEEVENTF_MOVE | MOUSEEVENTF_ABSOLUTE | 0x4000, time=0, dwExtraInfo=0)))
    user32.SendInput(1, ctypes.byref(inp), ctypes.sizeof(INPUT))

def send_mouse_click(button="left", x=None, y=None, hold_ms=65):
    if x is not None and y is not None:
        send_mouse_move(x, y)
    down_f = MOUSEEVENTF_LEFTDOWN if button == "left" else MOUSEEVENTF_RIGHTDOWN
    up_f = MOUSEEVENTF_LEFTUP if button == "left" else MOUSEEVENTF_RIGHTUP
    inp_d = INPUT(type=INPUT_MOUSE, u=_INPUT_UNION(mi=MOUSEINPUT(dx=0, dy=0, mouseData=0, dwFlags=down_f, time=0, dwExtraInfo=0)))
    inp_u = INPUT(type=INPUT_MOUSE, u=_INPUT_UNION(mi=MOUSEINPUT(dx=0, dy=0, mouseData=0, dwFlags=up_f, time=0, dwExtraInfo=0)))
    user32.SendInput(1, ctypes.byref(inp_d), ctypes.sizeof(INPUT))
    time.sleep(hold_ms / 1000.0)
    user32.SendInput(1, ctypes.byref(inp_u), ctypes.sizeof(INPUT))

def send_text(text):
    for c in text:
        code = ord(c)
        d = INPUT(type=INPUT_KEYBOARD, u=_INPUT_UNION(ki=KEYBDINPUT(wVk=0, wScan=code, dwFlags=KEYEVENTF_UNICODE, time=0, dwExtraInfo=0)))
        u = INPUT(type=INPUT_KEYBOARD, u=_INPUT_UNION(ki=KEYBDINPUT(wVk=0, wScan=code, dwFlags=KEYEVENTF_UNICODE | KEYEVENTF_KEYUP, time=0, dwExtraInfo=0)))
        user32.SendInput(1, ctypes.byref(d), ctypes.sizeof(INPUT))
        user32.SendInput(1, ctypes.byref(u), ctypes.sizeof(INPUT))
        time.sleep(0.045)

def move_windmouse(dest_x, dest_y, duration_ms=250):
    start_x, start_y = get_cursor_pos()
    steps = 40
    for i in range(steps + 1):
        t = i / float(steps)
        t_smooth = t * t * (3.0 - 2.0 * t)
        cx = int(round(start_x + (dest_x - start_x) * t_smooth))
        cy = int(round(start_y + (dest_y - start_y) * t_smooth))
        send_mouse_move(cx, cy)
        time.sleep((duration_ms / 1000.0) / steps)

def run_macro():
    print("Starting Shohoj Macro standalone playback in 2 seconds...")
    time.sleep(2)
    speed = {speed}
    total_loops = {loops}
    
    for loop in range(total_loops if total_loops > 0 else 999999):
        print(f"Executing Loop {{loop + 1}}...")
'''
        # Append action steps
        for ev in events:
            if not ev.enabled:
                continue
            t = ev.event_type
            if t == EventType.MOUSE_MOVE:
                script_content += f"        move_windmouse({ev.x}, {ev.y}, {ev.duration_ms / speed:.1f})\n"
            elif t == EventType.MOUSE_CLICK:
                script_content += f"        send_mouse_click('{ev.button}', {ev.x}, {ev.y})\n"
            elif t == EventType.TEXT_TYPE:
                safe_text = ev.text.replace("\\", "\\\\").replace('"', '\\"')
                script_content += f'        send_text("{safe_text}")\n'
            elif t == EventType.DELAY:
                script_content += f"        time.sleep({(ev.delay_ms / 1000.0) / speed:.3f})\n"

            if ev.delay_after_ms > 0:
                script_content += f"        time.sleep({(ev.delay_after_ms / 1000.0) / speed:.3f})\n"

        script_content += '''
    print("Macro playback finished successfully.")
    winmm.timeEndPeriod(1)

if __name__ == "__main__":
    run_macro()
'''
        try:
            with open(filepath, "w", encoding="utf-8") as f:
                f.write(script_content)
            return True
        except Exception as e:
            print(f"Error exporting Python script: {e}")
            return False

    @classmethod
    def export_to_ahk_script(cls, events: list[MacroEvent], filepath: str, loops: int = 1, speed: float = 1.0) -> bool:
        """
        Exports a functional AutoHotkey (.ahk) script.
        """
        ahk = f"""; Generated by {__app_name__} v{__version__}
; Developed by {__author__}
#NoEnv
SendMode Input
SetWorkingDir %A_ScriptDir%
CoordMode, Mouse, Screen

F9::
Loop, {loops if loops > 0 else 0}
{{
"""
        for ev in events:
            if not ev.enabled:
                continue
            t = ev.event_type
            if t == EventType.MOUSE_MOVE:
                ahk += f"    MouseMove, {ev.x}, {ev.y}, 2\n"
            elif t == EventType.MOUSE_CLICK:
                ahk += f"    MouseClick, {ev.button}, {ev.x}, {ev.y}\n"
            elif t == EventType.TEXT_TYPE:
                ahk += f"    SendRaw, {ev.text}\n"
            elif t == EventType.DELAY:
                ahk += f"    Sleep, {int(ev.delay_ms / speed)}\n"

            if ev.delay_after_ms > 0:
                ahk += f"    Sleep, {int(ev.delay_after_ms / speed)}\n"

        ahk += """}
return

F10::
ExitApp
"""
        try:
            with open(filepath, "w", encoding="utf-8") as f:
                f.write(ahk)
            return True
        except Exception as e:
            print(f"Error exporting AHK script: {e}")
            return False
